hmcts/ia-docker

compose/backend.yml
database/Dockerfile
database/init-db.sh

Adding the ia-case-api database as one of the project dependencies for dev
```
[ ] Yes
[x] No
```

Adding ia_case_db

---

ccd
compose/backend.yml
compose/frontend.yml

https://tools.hmcts.net/jira/browse/RIA-1653
See Jira
```
[ ] Yes
[ ] No
```

Ria 1653 docker registry upgrade

---

bin/authenticate.sh
bin/ccd-import-definition.sh
bin/create-role.sh
bin/create-service.sh
bin/create-user.sh
bin/idam-service-token.sh
bin/idam-user-token.sh
bin/register-role.sh
bin/setup.sh
compose/backend.yml
compose/defaults.conf
compose/dm-store.yml
compose/frontend.yml
compose/sidam.yml

[RIA-1721](https://tools.hmcts.net/jira/browse/RIA-1721)
tidam to sidam migration
```
[x] Yes
[ ] No
```

Tidam to sidam

---

bin/setup.sh
bin/wiremock.sh
compose/backend.yml

N/A
share case users and wiremock
```
[ ] Yes
[x] No
```

Share a case

---

bin/wiremock.sh

[RIA-2526](https://tools.hmcts.net/jira/browse/RIA-2526)
See Jira
```
[ ] Yes
[x] No
```

RIA-2526 downstream services health check

---

bin/setup.sh
compose/evidence-management.yml

N/A
EM openid settings
```
[ ] Yes
[x] No
```

EM openid settings

---

.local_env

N/A
launch darkly env variable
```
[ ] Yes
[x] No
```

launch darkly env variable

---

bin/wiremock.sh

[RIA-3006](https://tools.hmcts.net/jira/browse/RIA-3006)
Wire-mock fees-register api response for oral fees
```
[ ] Yes
[x] No
```

RIA-3006 Wire-mock response for oral fees

---

bin/create-service.sh
bin/idam-user-token.sh
bin/setup.sh

[RIA-1689](https://tools.hmcts.net/jira/browse/RIA-1689)
OpenId integration
```
[ ] Yes
[x] No
```

OpenId integration

---

database/Dockerfile
database/init-db.sh

RIA-2689
timed event service database
```
[ ] Yes
[x] No
```

RIA-2689 timed event service database

---

bin/wiremock.sh

RIA-3002 pba payment api wiremock setup

---

.local_env

https://tools.hmcts.net/jira/browse/RIA-2918

RIA-2918 add feature flag env var

---

bin/wiremock.sh

RIA-3374
pba ref data wiremock
```
[ ] Yes
[x] No
```

RIA-3374 pba ref data wiremock

---

compose/frontend.yml

[RIA-3281](https://tools.hmcts.net/jira/browse/RIA-3281)
See Jira
```
[ ] Yes
[x] No
```

RIA-3281 shuttering redirect to XUI

---

README.md
compose/backend.yml

[RIA-2691](https://tools.hmcts.net/jira/browse/RIA-2691)
timed event service
```
[ ] Yes
[x] No
```

RIA-2691 timed event service

---

compose/xui.yml

N/A
XUI new env variables
```
[ ] Yes
[x] No
```

XUI new env variables

---

.local_env
bin/setup.sh
bin/wiremock.sh

[RIA-3082](https://tools.hmcts.net/jira/browse/RIA-3082)
See Jira
```
[ ] Yes
[x] No
```

Ria 3082 submit appeal failed payment

---

compose/backend.yml

https://tools.hmcts.net/jira/browse/RIA-3380
Added homeoffice mock api to ia-docker
```
[ ] Yes
[X] No
```

RIA-3380: Added homeoffice mock api to ia-docker

---

.local_env

https://tools.hmcts.net/jira/browse/RIA-3454
RIA-3454: Notifications when application online decided
```
[ ] Yes
[ X] No
```

RIA-3454 add email email HO APC and LART

---

.local_env

https://tools.hmcts.net/jira/browse/RIA-3754
see jira
```
[ ] Yes
[X ] No
```

Add upper tribunal notices email to local env

---

.local_env

RIA-3689: Add payment exceptions AO email for notification in local_env
https://tools.hmcts.net/jira/browse/RIA-3689
```
[ ] Yes
[ x] No
```

RIA-3689: Add payment exceptions AO email for notification in local_env

---

bin/wiremock.sh

https://tools.hmcts.net/jira/browse/RWA-319

RWA-319 add role-assignment and ref-data mocks in wiremock

---

bin/setup.sh
bin/wiremock.sh
compose/backend.yml
compose/xui.yml

[RIA-3845](https://tools.hmcts.net/jira/browse/RIA-3845)
See Jira
```
[ ] Yes
[x] No
```

Ria 3845 setup initial permission

---

README.md
ccd
compose/dm-store.yml
compose/frontend.yml

N/A
remove deprecated CCD UI app
```
[ ] Yes
[x] No
```

remove deprecated CCD UI app

---

bin/setup.sh

https://tools.hmcts.net/jira/browse/RWA-275

RWA-275 add new role

---

compose/xui.yml

N/A
add new env variables ExUI
```
[ ] Yes
[x] No
```

add new env variables ExUI

---

bin/wiremock.sh

https://tools.hmcts.net/jira/browse/RWA-400

udpate ref data response

---

.local_env

RIA-3799
RIA-3799 add NBC and CTSC emails
```
[ ] Yes
[ X] No
```

RIA-3799 add NBC and CTSC emails

---

compose/dm-store.yml

CCD_DM_DOMAIN env variable updated to CCD_DOCUMENT_URL_PATTERN
```
[ ] Yes
[ ] No
```

New env variable updated for ccd_document_url_pattern

---

bin/setup.sh

Fixed srcaseofficer role
```
[ ] Yes
[X] No
```

Fixed srcaseofficer role

---

bin/setup.sh
bin/wiremock.sh

N/A
update fee codes in wiremock
```
[ ] Yes
[x] No
```

update fee codes in wiremock

---

bin/wiremock.sh

[RIA-4496](https://tools.hmcts.net/jira/browse/RIA-4496)
update fee keywords in wiremock
```
[ ] Yes
[x] No
```

RIA-4496 update fee keywords in wiremock

---

compose/backend.yml

N/A
Increase CCD timeout default
```
[ ] Yes
[x] No
```

Increase CCD timeout default

---

compose/backend.yml
compose/dm-store.yml

N/A
CCD new Idam variables, dm-store logger removal
```
[ ] Yes
[x] No
```

CCD new Idam variables, dm-store logger removal

---

compose/evidence-management.yml

N/A
Docmosis AAT IP change
```
[ ] Yes
[x] No
```

Docmosis AAT IP change

---

compose/xui.yml

N/A
XUI integration with CCD new documents API
```
[ ] Yes
[x] No
```

XUI integration with CCD new documents API

---

compose/backend.yml

N/A
whitelisting ccd_case_document_am
```
[ ] Yes
[x] No
```

whitelisting ccd_case_document_am

---

bin/wiremock.sh
compose/payments.yml

Setting for AIP  payament-history tab details

---

bin/setup.sh

[https://tools.hmcts.net/jira/browse/RIA-5569]
Adding homeofficebail role to the respondent user as part of the bails journey
```
[ ] Yes
[ X] No
```

RIA-5569 Adding homeofficebail role to respondent user

---

compose/elasticsearch.yml

Upgrade ES version after CCD Release 25.1

---

bin/ccd-add-access-profile.sh
bin/setup.sh

Add access profile

---

bin/organisational-role-assignment-judge.sh
bin/wa-create-users.sh
bin/wa-register-roles.sh
compose/backend.yml
compose/task-management.yml

Update branch with recent changes on WA-IA-integration-REBASED

---

bin/wa-register-roles.sh

New access role

---

bin/wiremock-languages.sh

https://tools.hmcts.net/jira/browse/RIA-7507
```
[ ] Yes
[x] No
```

RIA-7507: Include Sign languages in the ref data language mock

---

.hmc-env
bin/wa-create-users.sh
bin/wa-register-roles.sh
bin/wa-setup.sh
bin/wiremock-hearings-tab/run-all-wiremock-hearings-tab.sh
bin/wiremock-hearings-tab/wiremock-case-linking-reason-code.sh
bin/wiremock-hearings-tab/wiremock-caseflags-all-xui.sh
bin/wiremock-hearings-tab/wiremock-casetypes.sh
bin/wiremock-hearings-tab/wiremock-change-reasons.sh
bin/wiremock-hearings-tab/wiremock-court-venues.sh
bin/wiremock-hearings-tab/wiremock-facilities.sh
bin/wiremock-hearings-tab/wiremock-getLocationById-hatton-cross.sh
bin/wiremock-hearings-tab/wiremock-hearing-channels.sh
bin/wiremock-hearings-tab/wiremock-hearing-priority.sh
bin/wiremock-hearings-tab/wiremock-hearing-subchannels.sh
bin/wiremock-hearings-tab/wiremock-hearing-types.sh
bin/wiremock-hearings-tab/wiremock-judgetype.sh
bin/wiremock-hearings-tab/wiremock-lookup-hatton-cross.sh
bin/wiremock-hearings-tab/wiremock-panelmembertype.sh
compose/backend.yml
compose/hmi.yml
compose/xui.yml

[RIA-7860](https://tools.hmcts.net/jira/browse/RIA-7860)
- Added hmc specific roles to local users
- Added necessary extra environment variables
- Added all stubbed calls to Wiremock that XUI makes to the Ref Data services
```
[ ] Yes
[x] No
```

RIA-7860 hearings tab local setup

---

bin/wiremock-hearings-tab/run-all-wiremock-hearings-tab.sh
bin/wiremock-hearings-tab/wiremock-hearing-case-management-cancellation-reasons.sh

https://tools.hmcts.net/jira/browse/RIA-7745
Enable hearing cancellation feature
```
[ ] Yes
[X] No
```

RIA-7745 Add cancel hearing functionality

---

bin/wiremock-hearings-tab/wiremock-hearing-priority.sh
bin/wiremock-hearings-tab/wiremock-location-lookup.sh

https://tools.hmcts.net/jira/browse/RIA-7665
Fix hearings mapping failing locations 
Fix hearing priority duplicates
```
[ ] Yes
[X] No
```

RIA-7665 Fix hearing location and priorities issues.

---

bin/wa-create-users.sh

[RIA-7881](https://tools.hmcts.net/jira/browse/RIA-7881)
- give `listed-hearing-viewer` role to system user
```
[ ] Yes
[x] No
```

RIA-7881 listed-hearing-viewer role to system user

---

bin/wiremock-hearings-tab/wiremock-change-reasons.sh

https://tools.hmcts.net/jira/browse/RIA-7823
RIA-7823 update modify reasons id
```
[ ] Yes
[X] No
```

RIA-7823 update modify reasons id

---

bin/wiremock-hearings-tab/wiremock-facilities.sh

https://tools.hmcts.net/jira/browse/RIA-7918
RIA-7918 Add typeC facility to facilities wiremock
```
[ ] Yes
[X] No
```

RIA-7918 Add typeC facility to facilities wiremock

---

bin/wa-register-roles.sh

RIA-TASK - Added Case Flag Roles

RIA-TASK - Added Case Flag Roles

---

bin/wiremock-hearings-tab/wiremock-hearing-case-management-cancellation-reasons.sh

https://tools.hmcts.net/jira/browse/RIA-7799
RIA-7799 Update cancellation reasons ref data
```
[ ] Yes
[X] No
```

RIA-7799 Update cancellation reasons ref data

---

bin/wiremock-hearings-tab/wiremock-panelmembertype.sh

https://tools.hmcts.net/jira/browse/RIA-8202
RIA-8202 format correctly the panelMember wiremock
```
[ ] Yes
[ X] No
```

RIA-8202 format correctly the panelMember wiremock

---

bin/wiremock-hearings-tab/wiremock-list-location.sh

[https://tools.hmcts.net/jira/browse/RIA-7983](https://tools.hmcts.net/jira/browse/RIA-7983)
- Swap `service-code` parameter name for `service_code`

RIA-7983 Swap service-code parameter name for service_code

---

.wa-env
bin/organisational-role-assignment-nbc.sh
bin/wa-create-users.sh

https://tools.hmcts.net/jira/browse/RIA-8270
Added NBC admin role and user
```
[ ] Yes
[ x ] No
```

RIA-8270 Added NBC admin role and user

---

.local_env
bin/wa-create-users.sh

- [ x] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/RIA-9110
Add bails legal rep user for hearings api functional test
```
[ ] Yes
[ x] No
```

RIA-9110 - Add bails legal rep user for hearings api functional test
